name: example
description: Demonstration the usage of Flutter Mediator Lite.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.2

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_i18n: ^0.33.0
  flutter_mediator_lite:
    path: ../
  shared_preferences: ^2.1.1

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/trees.png
    - assets/flutter_i18n/
