name: flutter_mediator_lite
description: A super easy state management package, base on the InheritedModel with automatic aspect management.
version: 1.0.3
homepage: https://github.com/rob333/flutter_mediator_lite

environment:
  sdk: ">=2.14.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
